# lstm.
def get_settings_lstm(a):

  settings = {
    # Reference body model.
    "body_reference": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "learning_r": 0.0000551656748852718,
      "nHUnits": 128,
      "nHLayers": 3,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "bidirectional": False,
      "num_frames": 60,
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "h5": True,
      "sherlock": False,
      "loss_f": "weighted_l2_loss",
      "curated_datasets": True,
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2},
      "partial_selection": {"activity":["treadmillwalking", "cycling", "karate"], 
                            "factor":[2, 3, 2],
                            "excluded": [2]}
    },
    # Reference arm model.
    "arm_reference": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "learning_r": 0.0000551656748852718,
      "nHUnits": 128,
      "nHLayers": 4,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "bidirectional": False,
      "num_frames": 60,
      "h5": True,
      "sherlock": False,
      "curated_datasets": True,
      "partial_selection": {"activity":["cycling"], "factor":[2]}
    },
    # Example body model (only dataset 0).
    "body_example": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "learning_r": 0.0000551656748852718,
      "nHUnits": 128,
      "nHLayers": 3,
      "nEpochs": 50,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "bidirectional": False,
      "num_frames": 60,
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "h5": True,
      "sherlock": False,
      "loss_f": "weighted_l2_loss",
      "curated_datasets": True,
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2}
    },
    # Example arm model (only dataset 0).
    "arm_example": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "learning_r": 0.0000551656748852718,
      "nHUnits": 128,
      "nHLayers": 4,
      "nEpochs": 50,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "bidirectional": False,
      "num_frames": 60,
      "h5": True,
      "sherlock": False,
      "curated_datasets": True
    },
  }

  return settings[str(a)]

# Transformer.
def get_settings_transformer(a):
  settings = {
    # Reference body model.
    "body_reference": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "nHLayers": 2,
      "nHeads": 4,
      "d_model": 256,
      "d_ff": 1024,
      "d_k": 64,
      "d_v": 64,
      "attention_axes": None,
      "dropout": 0,
      "nEpochs": 100,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "model_type": "Transformer",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},          
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},          
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "partial_selection": {"activity":["treadmillwalking", "cycling", "karate"], 
                        "factor":[2, 3, 2],
                        "excluded": [2]},
      "encoder_only": True,
      "loss_f": "weighted_l2_loss",
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2}
    },
    # Reference arm model.
    "arm_reference": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "nHLayers": 2,
      "nHeads": 4,
      "d_model": 256,
      "d_ff": 1024,
      "d_k": 64,
      "d_v": 64,
      "attention_axes": None,
      "dropout": 0,
      "nEpochs": 100,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "model_type": "Transformer",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},          
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},          
      "partial_selection": {"activity":["cycling"], "factor":[2]},
      "encoder_only": True
    },
    # Example body model (only dataset 0).
    "body_example": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "nHLayers": 2,
      "nHeads": 4,
      "d_model": 256,
      "d_ff": 1024,
      "d_k": 64,
      "d_v": 64,
      "attention_axes": None,
      "dropout": 0,
      "nEpochs": 100,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "model_type": "Transformer",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},          
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},          
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "encoder_only": True,
      "loss_f": "weighted_l2_loss",
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2}
    },
    # Example arm model (only dataset 0).
    "arm_example": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "different_data_val_loss": True,
      "nHLayers": 2,
      "nHeads": 4,
      "d_model": 256,
      "d_ff": 1024,
      "d_k": 64,
      "d_v": 64,
      "attention_axes": None,
      "dropout": 0,
      "nEpochs": 100,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "model_type": "Transformer",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},          
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},          
      "encoder_only": True
    }
  }
          
  return settings[str(a)]

# Linear.
def get_settings_linear(a):          
  settings = {
    # Reference body model.
    "body_reference": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "learning_r": 0.0000551656748852718,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "different_data_val_loss": True,
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},
      "bidirectional": False,
      "num_frames": 60,
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "h5": True,
      "sherlock": False,
      "loss_f": "weighted_l2_loss",
      "curated_datasets": True,
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2},
      "partial_selection": {"activity":["treadmillwalking", "cycling", "karate"], 
                            "factor":[2, 3, 2],
                            "excluded": [2]}
    },
    # Reference arm model.
    "arm_reference": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [idx for idx in range(0,29) if not idx in [3,4,6,12]],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "learning_r": 0.0000551656748852718,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "different_data_val_loss": True,
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},
      "bidirectional": False,
      "num_frames": 60,
      "h5": True,
      "sherlock": False,
      "curated_datasets": True,
      "partial_selection": {"activity":["cycling"], "factor":[2]}
    },
    # Example body model (only dataset 0).
    "body_example": {
      "augmenter_type": "lowerExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "learning_r": 0.0000551656748852718,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "different_data_val_loss": True,
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},
      "bidirectional": False,
      "num_frames": 60,
      "sampling_frequencies": {"Dataset": [2], "fs": [100]},
      "h5": True,
      "sherlock": False,
      "loss_f": "weighted_l2_loss",
      "curated_datasets": True,
      "marker_weights": {"RToe_augmenter": 2,
                        "R5meta_augmenter": 2,
                        "RCalc_augmenter": 2,
                        "LToe_augmenter": 2,
                        "L5meta_augmenter": 2,
                        "LCalc_augmenter": 2},
    },
    # Example arm model (only dataset 0).
    "arm_example": {
      "augmenter_type": "upperExtremity",
      "poseDetector": "openpose",
      "idxDatasets": [0],
      "scaleFactors": [0.9, 0.95, 1., 1.05, 1.1],
      "nScaleFactors": -1,
      "learning_r": 0.0000551656748852718,
      "nEpochs": 30,
      "batchSize": 64,
      "mean_subtraction": True,
      "std_normalization": True,
      "noise_magnitude": 0.018,
      "noise_type": "per_timestep",
      "withRotation": True,
      "nRotations": 8,
      "rotation_type": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations" : {"nCircleRotations": 6, "nSphereRotations": 2},
      "different_data_val_loss": True,
      "withRotation_val_loss": True,
      "nRotations_val_loss": 4,
      "rotation_type_val_loss": "mixedCircleSphereRotation",
      "mixedCircleSphereRotations_val_loss" : {"nCircleRotations": 3, "nSphereRotations": 1},
      "bidirectional": False,
      "num_frames": 60,
      "h5": True,
      "sherlock": False,
      "curated_datasets": True
    }
  }

  return settings[str(a)]
